import Link from '@/components/Link'
import { slug } from 'github-slugger'
import { genPageMetadata } from 'app/seo'

// This will be generated by contentlayer
let tagDataCategorized: {
  counts: { artist: Record<string, number> }
  displayValues: { artist: Record<string, string> }
} = { counts: { artist: {} }, displayValues: { artist: {} } }

try {
  tagDataCategorized = require('app/tag-data-categorized.json')
} catch {
  // File doesn't exist yet, will be created by contentlayer
}

export const metadata = genPageMetadata({
  title: 'Artists',
  description: 'Browse artworks by artist',
})

export default async function Page() {
  const artistCounts = tagDataCategorized.counts?.artist || {}
  const artistDisplayValues = tagDataCategorized.displayValues?.artist || {}
  const artistKeys = Object.keys(artistCounts)
  const sortedArtists = artistKeys.sort((a, b) => {
    // Sort alphabetically by display value
    const nameA = artistDisplayValues[a] || a
    const nameB = artistDisplayValues[b] || b
    return nameA.localeCompare(nameB)
  })

  return (
    <>
      <div className="flex flex-col items-start justify-start divide-y divide-gray-200 dark:divide-gray-700 md:mt-24 md:flex-row md:items-center md:justify-center md:space-x-6 md:divide-y-0">
        <div className="space-x-2 pb-8 pt-6 md:space-y-5">
          <h1 className="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:border-r-2 md:px-6 md:text-6xl md:leading-14">
            Artists
          </h1>
        </div>
        <div className="flex max-w-lg flex-wrap">
          {artistKeys.length === 0 && 'No artists found.'}
          {sortedArtists.map((artistSlug) => {
            const displayName = artistDisplayValues[artistSlug] || artistSlug
            return (
              <div key={artistSlug} className="mb-2 mr-5 mt-2">
                <Link
                  href={`/artists/${artistSlug}`}
                  className="mr-3 text-sm font-medium text-primary-500 hover:text-primary-600 dark:hover:text-primary-400"
                >
                  {displayName}
                </Link>
                <span className="-ml-2 text-sm font-semibold uppercase text-gray-600 dark:text-gray-300">
                  {` (${artistCounts[artistSlug]})`}
                </span>
              </div>
            )
          })}
        </div>
      </div>
    </>
  )
}
