import { allCoreContent, sortPosts } from 'pliny/utils/contentlayer'
import siteMetadata from '@/data/siteMetadata'
import ListLayout from '@/layouts/ListLayoutWithTags'
import { allBlogs } from 'contentlayer/generated'
import { genPageMetadata } from 'app/seo'
import { Metadata } from 'next'
import { parseTag } from '@/lib/tagUtils'

// This will be generated by contentlayer
let tagDataCategorized: {
  counts: { movement: Record<string, number> }
  displayValues: { movement: Record<string, string> }
} = { counts: { movement: {} }, displayValues: { movement: {} } }

try {
  tagDataCategorized = require('app/tag-data-categorized.json')
} catch {
  // File doesn't exist yet
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ movement: string }>
}): Promise<Metadata> {
  const { movement } = await params
  const movementSlug = decodeURI(movement)
  const displayName = tagDataCategorized.displayValues?.movement?.[movementSlug] || movementSlug
  return genPageMetadata({
    title: displayName,
    description: `${siteMetadata.title} - ${displayName} artworks`,
    alternates: {
      canonical: './',
      types: {
        'application/rss+xml': `${siteMetadata.siteUrl}/movements/${movementSlug}/feed.xml`,
      },
    },
  })
}

export const dynamicParams = false

export const generateStaticParams = async () => {
  const movementCounts = tagDataCategorized.counts?.movement || {}
  const paths = Object.keys(movementCounts).map((movement) => ({
    movement: movement,
  }))
  return paths
}

export default async function MovementPage({ params }: { params: Promise<{ movement: string }> }) {
  const { movement } = await params
  const movementSlug = decodeURI(movement)
  const displayName = tagDataCategorized.displayValues?.movement?.[movementSlug] || movementSlug
  const title = displayName

  // Filter posts that have this movement tag
  const filteredPosts = allCoreContent(
    sortPosts(
      allBlogs.filter(
        (post) =>
          post.tags &&
          post.tags.some((tag) => {
            const parsed = parseTag(tag)
            return parsed.category === 'movement' && parsed.slug === movementSlug
          })
      )
    )
  )

  return <ListLayout posts={filteredPosts} title={title} />
}
