import Link from '@/components/Link'
import { genPageMetadata } from 'app/seo'

// This will be generated by contentlayer
let tagDataCategorized: {
  counts: { movement: Record<string, number> }
  displayValues: { movement: Record<string, string> }
} = { counts: { movement: {} }, displayValues: { movement: {} } }

try {
  tagDataCategorized = require('app/tag-data-categorized.json')
} catch {
  // File doesn't exist yet
}

export const metadata = genPageMetadata({
  title: 'Movements',
  description: 'Browse artworks by artistic movement',
})

export default async function Page() {
  const movementCounts = tagDataCategorized.counts?.movement || {}
  const movementDisplayValues = tagDataCategorized.displayValues?.movement || {}
  const movementKeys = Object.keys(movementCounts)
  const sortedMovements = movementKeys.sort((a, b) => {
    // Sort by count (most works first)
    return movementCounts[b] - movementCounts[a]
  })

  return (
    <>
      <div className="flex flex-col items-start justify-start divide-y divide-gray-200 dark:divide-gray-700 md:mt-24 md:flex-row md:items-center md:justify-center md:space-x-6 md:divide-y-0">
        <div className="space-x-2 pb-8 pt-6 md:space-y-5">
          <h1 className="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:border-r-2 md:px-6 md:text-6xl md:leading-14">
            Movements
          </h1>
        </div>
        <div className="flex max-w-lg flex-wrap">
          {movementKeys.length === 0 && 'No movements found.'}
          {sortedMovements.map((movementSlug) => {
            const displayName = movementDisplayValues[movementSlug] || movementSlug
            return (
              <div key={movementSlug} className="mb-2 mr-5 mt-2">
                <Link
                  href={`/movements/${movementSlug}`}
                  className="mr-3 text-sm font-medium text-primary-500 hover:text-primary-600 dark:hover:text-primary-400"
                >
                  {displayName}
                </Link>
                <span className="-ml-2 text-sm font-semibold uppercase text-gray-600 dark:text-gray-300">
                  {` (${movementCounts[movementSlug]})`}
                </span>
              </div>
            )
          })}
        </div>
      </div>
    </>
  )
}
