import Link from '@/components/Link'
import { genPageMetadata } from 'app/seo'

// This will be generated by contentlayer
let tagDataCategorized: {
  counts: { location: Record<string, number> }
  displayValues: { location: Record<string, string> }
} = { counts: { location: {} }, displayValues: { location: {} } }

try {
  tagDataCategorized = require('app/tag-data-categorized.json')
} catch {
  // File doesn't exist yet
}

export const metadata = genPageMetadata({
  title: 'Locations',
  description: 'Browse artworks by museum and location',
})

export default async function Page() {
  const locationCounts = tagDataCategorized.counts?.location || {}
  const locationDisplayValues = tagDataCategorized.displayValues?.location || {}
  const locationKeys = Object.keys(locationCounts)
  const sortedLocations = locationKeys.sort((a, b) => {
    // Sort alphabetically by display value
    const nameA = locationDisplayValues[a] || a
    const nameB = locationDisplayValues[b] || b
    return nameA.localeCompare(nameB)
  })

  return (
    <>
      <div className="flex flex-col items-start justify-start divide-y divide-gray-200 dark:divide-gray-700 md:mt-24 md:flex-row md:items-center md:justify-center md:space-x-6 md:divide-y-0">
        <div className="space-x-2 pb-8 pt-6 md:space-y-5">
          <h1 className="text-3xl font-extrabold leading-9 tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl sm:leading-10 md:border-r-2 md:px-6 md:text-6xl md:leading-14">
            Locations
          </h1>
        </div>
        <div className="flex max-w-lg flex-wrap">
          {locationKeys.length === 0 && 'No locations found.'}
          {sortedLocations.map((locationSlug) => {
            const displayName = locationDisplayValues[locationSlug] || locationSlug
            return (
              <div key={locationSlug} className="mb-2 mr-5 mt-2">
                <Link
                  href={`/locations/${locationSlug}`}
                  className="mr-3 text-sm font-medium text-primary-500 hover:text-primary-600 dark:hover:text-primary-400"
                >
                  {displayName}
                </Link>
                <span className="-ml-2 text-sm font-semibold uppercase text-gray-600 dark:text-gray-300">
                  {` (${locationCounts[locationSlug]})`}
                </span>
              </div>
            )
          })}
        </div>
      </div>
    </>
  )
}
