import { slug } from 'github-slugger'
import { allCoreContent, sortPosts } from 'pliny/utils/contentlayer'
import siteMetadata from '@/data/siteMetadata'
import ListLayout from '@/layouts/ListLayoutWithTags'
import { allBlogs } from 'contentlayer/generated'
import { genPageMetadata } from 'app/seo'
import { Metadata } from 'next'
import { parseTag } from '@/lib/tagUtils'

// This will be generated by contentlayer
let tagDataCategorized: {
  counts: { artist: Record<string, number> }
  displayValues: { artist: Record<string, string> }
} = { counts: { artist: {} }, displayValues: { artist: {} } }

try {
  tagDataCategorized = require('app/tag-data-categorized.json')
} catch {
  // File doesn't exist yet
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ artist: string }>
}): Promise<Metadata> {
  const { artist } = await params
  const artistSlug = decodeURI(artist)
  const displayName = tagDataCategorized.displayValues?.artist?.[artistSlug] || artistSlug
  return genPageMetadata({
    title: displayName,
    description: `${siteMetadata.title} - works by ${displayName}`,
    alternates: {
      canonical: './',
      types: {
        'application/rss+xml': `${siteMetadata.siteUrl}/artists/${artistSlug}/feed.xml`,
      },
    },
  })
}

export const dynamicParams = false

export const generateStaticParams = async () => {
  const artistCounts = tagDataCategorized.counts?.artist || {}
  const paths = Object.keys(artistCounts).map((artist) => ({
    artist: artist,
  }))
  return paths
}

export default async function ArtistPage({ params }: { params: Promise<{ artist: string }> }) {
  const { artist } = await params
  const artistSlug = decodeURI(artist)
  const displayName = tagDataCategorized.displayValues?.artist?.[artistSlug] || artistSlug
  const title = displayName

  // Filter posts that have this artist tag
  const filteredPosts = allCoreContent(
    sortPosts(
      allBlogs.filter(
        (post) =>
          post.tags &&
          post.tags.some((tag) => {
            const parsed = parseTag(tag)
            return parsed.category === 'artist' && parsed.slug === artistSlug
          })
      )
    )
  )

  return <ListLayout posts={filteredPosts} title={title} />
}
