import { allCoreContent, sortPosts } from 'pliny/utils/contentlayer'
import siteMetadata from '@/data/siteMetadata'
import ListLayout from '@/layouts/ListLayoutWithTags'
import { allBlogs } from 'contentlayer/generated'
import { genPageMetadata } from 'app/seo'
import { Metadata } from 'next'
import { parseTag } from '@/lib/tagUtils'

// This will be generated by contentlayer
let tagDataCategorized: {
  counts: { location: Record<string, number> }
  displayValues: { location: Record<string, string> }
} = { counts: { location: {} }, displayValues: { location: {} } }

try {
  tagDataCategorized = require('app/tag-data-categorized.json')
} catch {
  // File doesn't exist yet
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ location: string }>
}): Promise<Metadata> {
  const { location } = await params
  const locationSlug = decodeURI(location)
  const displayName = tagDataCategorized.displayValues?.location?.[locationSlug] || locationSlug
  return genPageMetadata({
    title: displayName,
    description: `${siteMetadata.title} - artworks at ${displayName}`,
    alternates: {
      canonical: './',
      types: {
        'application/rss+xml': `${siteMetadata.siteUrl}/locations/${locationSlug}/feed.xml`,
      },
    },
  })
}

export const dynamicParams = false

export const generateStaticParams = async () => {
  const locationCounts = tagDataCategorized.counts?.location || {}
  const paths = Object.keys(locationCounts).map((location) => ({
    location: location,
  }))
  return paths
}

export default async function LocationPage({ params }: { params: Promise<{ location: string }> }) {
  const { location } = await params
  const locationSlug = decodeURI(location)
  const displayName = tagDataCategorized.displayValues?.location?.[locationSlug] || locationSlug
  const title = displayName

  // Filter posts that have this location tag
  const filteredPosts = allCoreContent(
    sortPosts(
      allBlogs.filter(
        (post) =>
          post.tags &&
          post.tags.some((tag) => {
            const parsed = parseTag(tag)
            return parsed.category === 'location' && parsed.slug === locationSlug
          })
      )
    )
  )

  return <ListLayout posts={filteredPosts} title={title} />
}
